// Auto-generated by onboarding optimizer agent
// Do not edit manually — changes will be overwritten on next agent run

export const onboardingConfig = {
  activeVariant: "A" as const,
  flaggedStepIndex: 7,
  lastUpdated: "2026-04-02T19:38:35.771Z",
} satisfies OnboardingConfig

type OnboardingConfig = {
  activeVariant: "A" | "B" | "C"
  flaggedStepIndex: number
  lastUpdated: string
}
